#include QMK_KEYBOARD_H

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

	[0] = LAYOUT_numpad_17(
		LT(1,KC_NUM), KC_PSLS, KC_PAST, KC_PMNS,
		KC_P7, KC_P8, KC_P9,
		KC_P4, KC_P5, KC_P6, KC_PPLS,
		KC_P1, KC_P2, KC_P3,
		KC_P0, KC_PDOT, KC_PENT),

	[1] = LAYOUT_numpad_17(
		KC_TRNS, RM_TOGG, RM_NEXT, RM_PREV,
		RM_HUEU, RM_HUED, KC_TRNS,
		RM_SATU, RM_SATD, KC_TRNS, KC_TRNS,
		RM_VALU, RM_VALD, KC_TRNS,
		RM_SPDU, RM_SPDD, KC_TRNS)


};
